name: apply

concurrency:
  group: apply

on:
  workflow_dispatch: ~

permissions:
  id-token: write
  contents: read

jobs:
  apply_release:
    uses: nodis-com-br/github-actions-workflows/.github/workflows/deploy-helm-releases.yaml@main
    with:
      vault_k8s_role_path: ${{ vars.vault_k8s_role_path }}
    secrets:
      OPENVPN_CONFIG: ${{ secrets.OPENVPN_CONFIG }}