name: apply

on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - '.github/**'
      - '*/*'

permissions:
  id-token: write
  contents: read

jobs:
  detect_changes:
    uses: nodis-com-br/github-actions-workflows/.github/workflows/detect-changes.yaml@main
  apply_releases:
    runs-on: ubuntu-latest
    if: needs.detect_changes.outputs.changes != '[]'
    needs:
      - detect_changes
    strategy:
      matrix:
        release: ${{ fromJSON(needs.detect_changes.outputs.changes) }}
    steps:
      - run: env | sort
      - uses: actions/checkout@v3
      - run: echo "ENVIRONMENT=$(echo ${{ matrix.release }} | awk -F/ '{print $1}')" | tee -a $GITHUB_ENV
      - run: echo "NAMESPACE=$(echo ${{ matrix.release }} | awk -F/ '{print $2}')" | tee -a $GITHUB_ENV
      - run: echo "RELEASE=$(echo ${{ matrix.release }} | awk -F/ '{print $3}')" | tee -a $GITHUB_ENV
      - run: echo "VAULT_K8S_ROLE_PATH=$(cat ${{ github.workspace }}/${ENVIRONMENT}/vault_k8s_role_path)" | tee -a $GITHUB_ENV
      - uses: ptonini/gha-openvpn@main
        with:
          openvpn_config: ${{ secrets.OPENVPN_CONFIG }}
          validation_addr: ${{ vars.vault_addr }}
      - uses: hashicorp/vault-action@v2.4.3
        with:
          url: ${{ vars.vault_addr }}
          method: ${{ vars.vault_method }}
          path: ${{ vars.vault_path }}
          role: ${{ vars.vault_role }}
          secrets: ${{ env.VAULT_K8S_ROLE_PATH }} kube_config | KUBECONFIG_CONTENT;
      - uses: ptonini/gha-deploy-helm-releases@main
        with:
          base_dir: ${{ github.workspace }}/${{ env.ENVIRONMENT }}/${{ env.NAMESPACE }}
          releases: ${{ env.RELEASE }}
          kubeconfig_content: ${{ env.KUBECONFIG_CONTENT }}