name: apply

on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - '.github/**'
      - '*'

jobs:
  detect_changes:
    uses: ptonini/gha-workflows/.github/workflows/detect-changes.yaml@main
  
  apply_releases:
    uses: ptonini/gha-workflows/.github/workflows/apply-helm-release.yaml@main
    if: needs.detect_changes.outputs.changes != '[]'
    needs:
      - detect_changes
    strategy:
      matrix:
        release: ${{ fromJSON(needs.detect_changes.outputs.changes) }}
    with:
      release: ${{ matrix.release }}
    secrets: inherit