name: apply

concurrency:
  group: apply

on:
  workflow_dispatch: ~

permissions:
  id-token: write
  contents: read

jobs:
  start:
    uses: ptonini/gha-workflows/.github/workflows/start.yaml@main
    secrets:
      VAULT_K8S_ROLE_PATHS: ${{ secrets.VAULT_K8S_ROLE_PATHS }}
  apply_release:
    uses: ptonini/gha-workflows/.github/workflows/deploy-helm-releases.yaml@main
    needs:
      - start
    secrets:
      OPENVPN_CONFIG: ${{ secrets.OPENVPN_CONFIG }}
      VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
      VAULT_K8S_ROLE_PATH: ${{ needs.start.outputs.vault_k8s_role_path }}