name: apply

concurrency:
  group: ${{ github.repository }}

on:
  workflow_dispatch: ~
  push:
    branches:
      - master
      - main
    paths-ignore:
      - '.github/workflows/*'

permissions:
  id-token: write
  contents: read

jobs:
  plan:
    uses: ptonini/gha-workflows/.github/workflows/terraform-plan.yaml@main
    secrets:
      OPENVPN_CONFIG: ${{ secrets.OPENVPN_CONFIG }}
  apply:
    uses: ptonini/gha-workflows/.github/workflows/terraform-apply.yaml@main
    if: needs.plan.outputs.exitcode == '2'
    needs:
      - plan
    secrets:
      OPENVPN_CONFIG: ${{ secrets.OPENVPN_CONFIG }}