name: apply

concurrency:
  group: apply

on:
  workflow_dispatch: ~

permissions:
  id-token: write
  contents: read

jobs:
  apply_release:
    uses: ptonini/gha-workflows/.github/workflows/deploy-helm-releases.yaml@main
    secrets:
      OPENVPN_CONFIG: ${{ secrets.OPENVPN_CONFIG }}
      GH_READER_TOKEN: ${{ secrets.GH_READER_TOKEN }}
