name: apply

concurrency:
  group: apply

on:
  workflow_dispatch: ~

jobs:
  startup:
    uses: ptonini/gha-workflows/.github/workflows/startup.yaml@main
    secrets:
      ORG_CONFIG: ${{ secrets.ORG_CONFIG }}
  apply_release:
    uses: ptonini/gha-workflows/.github/workflows/deploy-helm-releases.yaml@main
    needs:
      - startup
    secrets: inherit
  