name: apply

concurrency:
  group: ${{ github.repository }}

on:
  pull_request:
    types:
      - opened
      - synchronize
      - closed
    branches:
      - main
    paths-ignore:
      - '.github/workflows/*'

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:

  code_linting:
    uses: nodis-com-br/github-actions-workflows/.github/workflows/code-linting.yaml@main
    if: contains('opened synchronize', github.event.action) && vars.skip_linting != 'true'
  security_scan:
    uses: nodis-com-br/github-actions-workflows/.github/workflows/trufflehog.yaml@main
    if: contains('opened synchronize', github.event.action)

  plan:
    uses: nodis-com-br/github-actions-workflows/.github/workflows/terraform-plan.yaml@main
    if: contains('opened synchronize', github.event.action)
    secrets:
      OPENVPN_CONFIG: ${{ secrets.OPENVPN_CONFIG }}
      OPENSTACK_CONFIG: ${{ secrets.OPENVPN_CONFIG }}
      GH_TOKEN: ${{}}

  apply:
    uses: nodis-com-br/github-actions-workflows/.github/workflows/terraform-apply.yaml@main
    if: github.event.pull_request.merged && contains(github.event.pull_request.labels.*.name, 'plan_created')
    secrets:
      OPENVPN_CONFIG: ${{ secrets.OPENVPN_CONFIG }}
      OPENSTACK_CONFIG: ${{ secrets.OPENVPN_CONFIG }}
      GH_TOKEN: ${{}}