name: apply

concurrency:
  group: apply

on:
  workflow_dispatch: ~

permissions:
  id-token: write
  contents: read

jobs:
  apply_release:
    uses: ptonini/gha-workflows/.github/workflows/deploy-helm-releases.yaml@main
    with:
      macros: ${{ vars.macros }}
      vault_k8s_role_path: ${{ vars.vault_k8s_role_path }}
      aws_role: ${{ vars.aws_role }}
      aws_eks_cluster: ${{ vars.aws_eks_cluster }}
    secrets:
      OPENVPN_CONFIG: ${{ secrets.OPENVPN_CONFIG }}