name: demonstrate

concurrency:
  group: demonstrate

on:
  pull_request:
    types:
      - opened
      - synchronize
      - closed
    branches:
      - master
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy_demonstration:
    uses: ptonini/gha-workflows/.github/workflows/deploy-helm-releases.yaml@main
    if: contains('opened synchronize', github.event.action)
    with:
      macros: ${{ vars.macros }}
      vault_k8s_role_path: ${{ vars.vault_k8s_staging_role_path }}
    secrets:
      OPENVPN_CONFIG: ${{ secrets.OPENVPN_CONFIG }}
  destroy_demonstration:
    uses: ptonini/gha-workflows/.github/workflows/destroy-staging.yaml@main
    if: github.event.action == 'closed'
    with:
      vault_k8s_role_path: ${{ vars.vault_k8s_staging_role_path }}
    secrets:
      OPENVPN_CONFIG: ${{ secrets.OPENVPN_CONFIG }}