name: deploy

concurrency:
  group: ${{ github.event_name }}

on:
  push:
    branches:
      - master
      - main
      - legacy/*
    paths-ignore:
      - manifest.yaml
  pull_request:
    types:
      - opened
      - synchronize
      - closed
    branches:
      - master
      - main
      - legacy/*

jobs:
  release_please:
    uses: ptonini/gha-workflows/.github/workflows/release-please.yaml@main
    if: github.event_name == 'push'
  
  startup:
    uses: ptonini/gha-workflows/.github/workflows/startup.yaml@main
    if: (!contains(github.event.pull_request.head.ref, 'release-please--'))
    secrets:
      ORG_CONFIG: ${{ secrets.ORG_CONFIG }}
  
  publish_candidate:
    uses: ptonini/gha-workflows/.github/workflows/publish-docker-image.yaml@main
    if: needs.startup.outputs.publish_candidate == 'true'
    needs:
      - startup
    with:
      tags: ${{ format('latest pr{0}', github.event.number) }}
    secrets:
      BUILD_PASSWORD: ${{ secrets.GH_PACKAGES_TOKEN }}
  create_staging:
    uses: ptonini/gha-workflows/.github/workflows/deploy-helm-releases.yaml@main
    if: needs.startup.outputs.create_staging == 'true'
    needs:
      - startup
      - publish_candidate
    with:
      checksum: ${{ needs.publish_candidate.outputs.checksum }}
    secrets:
      OPENVPN_CONFIG: ${{ secrets.OPENVPN_CONFIG }}
      VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
      VAULT_APPROLE_ROLE_ID: ${{ secrets.VAULT_APPROLE_ROLE_ID }}
      VAULT_APPROLE_SECRET_ID: ${{ secrets.VAULT_APPROLE_SECRET_ID }}

  destroy_staging:
    uses: ptonini/gha-workflows/.github/workflows/destroy-staging.yaml@main
    if: needs.startup.outputs.destroy_staging == 'true'
    needs:
      - startup
    secrets:
      OPENVPN_CONFIG: ${{ secrets.OPENVPN_CONFIG }}
      VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
      VAULT_APPROLE_ROLE_ID: ${{ secrets.VAULT_APPROLE_ROLE_ID }}
      VAULT_APPROLE_SECRET_ID: ${{ secrets.VAULT_APPROLE_SECRET_ID }}
   
  publish_frontend:
    uses: ptonini/gha-workflows/.github/workflows/publish-frontend.yaml@main
    if: needs.release_please.outputs.release_created == 'true'
    needs:
      - startup
      - release_please
    with:
      tag_name: ${{ needs.release_please.outputs.tag_name }}
  deploy_frontend:
    uses: ptonini/gha-workflows/.github/workflows/deploy-frontend.yaml@main
    needs:
      - publish_frontend
      - release_please
    with:
      tag_name: ${{ needs.release_please.outputs.tag_name }}
    secrets:
      OPENVPN_CONFIG: ${{ secrets.OPENVPN_CONFIG }}
      VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
      VAULT_APPROLE_ROLE_ID: ${{ secrets.VAULT_APPROLE_ROLE_ID }}
      VAULT_APPROLE_SECRET_ID: ${{ secrets.VAULT_APPROLE_SECRET_ID }}
  
  unit_tests:
    uses: ptonini/gha-workflows/.github/workflows/unit-tests.yaml@main
    if: needs.startup.outputs.skip_tests == 'false'
    needs:
      - startup
  quality_scan:
    uses: ptonini/gha-workflows/.github/workflows/sonarcloud.yaml@main
    needs:
      - unit_tests
    secrets:
      GH_PACKAGES_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  
  code_linting:
    uses: ptonini/gha-workflows/.github/workflows/code-linting.yaml@main
    if: needs.startup.outputs.housekeeping == 'true'
    needs:
      - startup
  security_leaks_scan:
    uses: ptonini/gha-workflows/.github/workflows/trufflehog.yaml@main
    if: needs.startup.outputs.housekeeping == 'true'
    needs:
      - startup