name: deploy

concurrency:
  group: ${{ github.event_name }}

on:
  push:
    branches:
      - master
      - main
      - legacy/*
    paths-ignore:
      - manifest.yaml
  pull_request:
    types:
      - opened
      - synchronize
      - closed
    branches:
      - master
      - main
      - legacy/*

permissions:
  id-token: write
  packages: write
  pull-requests: write
  contents: write

jobs:
  
  code_testing:
    uses: ptonini/gha-workflows/.github/workflows/code-testing.yaml@main
    if: github.event.action != 'closed' && github.event.head_commit.author.name != 'github-actions[bot]' && !contains(github.event.repository.topics, 'skip-testing')
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  code_linting:
    uses: ptonini/gha-workflows/.github/workflows/code-linting.yaml@main
    if: github.event_name == 'pull_request' && contains('opened synchronize', github.event.action) && !contains(github.event.repository.topics, 'skip-linting')
  security_scan:
    uses: ptonini/gha-workflows/.github/workflows/trufflehog.yaml@main
    if: github.event_name == 'pull_request' && contains('opened synchronize', github.event.action)
  release_please:
    uses: ptonini/gha-workflows/.github/workflows/release-please.yaml@main
    if: github.event_name == 'push'
  
  start:
    uses: ptonini/gha-workflows/.github/workflows/start.yaml@main
    if: (!startsWith(github.event.pull_request.head.ref, 'release-please--'))
    with:
      vault_k8s_role_paths: ${{ vars.vault_k8s_role_paths }}
  
  build_candidate:
    uses: ptonini/gha-workflows/.github/workflows/publish-docker-image.yaml@main
    if:  github.event_name == 'pull_request' && contains('opened synchronize', github.event.action)
    needs:
      - start
    with:
      repository: ${{ format('{0}/{1}', vars.container_registry, github.event.repository.name ) }}
      tags: ${{ format('latest pr{0}', github.event.number) }}
    secrets:
      BUILD_ARGUMENTS: |
        BUILD_USERNAME=${{ github.actor }}
        BUILD_PASSWORD=${{ secrets.GH_PACKAGES_TOKEN }}
  deploy_staging:
    uses: ptonini/gha-workflows/.github/workflows/deploy-helm-releases.yaml@main
    if: (!contains(github.event.repository.topics, 'skip-staging'))
    needs:
      - build_candidate
    with:
      namespace: ${{ format('{0}-{1}', github.event.repository.name, github.event.number) }}
      digest: ${{ needs.build_candidate.outputs.digest }}
      environment: ${{ vars.staging_environment }}
      org_domain: ${{ vars.org_domain }}
      app_groups: ${{ vars.app_groups }}
      vault_addr: ${{ vars.vault_addr }}
      vault_k8s_role_path: ${{ vars.vault_k8s_staging_role_path }}
      vault_github_token_path: ${{ vars.vault_github_token_path }}
    secrets:
      OPENVPN_CONFIG: ${{ secrets.OPENVPN_CONFIG }}
  performance_testing:
    uses: ptonini/gha-workflows/.github/workflows/performance-testing.yaml@main
    needs:
      - deploy_staging
    with:
      filename: k6-tests.js
      hostnames: ${{ needs.deploy_staging.outputs.hostnames }}
  
  destroy_staging:
    uses: ptonini/gha-workflows/.github/workflows/destroy-staging.yaml@main
    if:  github.event_name == 'pull_request' && github.event.action == 'closed' && !contains(github.event.repository.topics, 'skip-staging')
    needs:
      - start
    with:
      namespace: ${{ format('{0}-{1}', github.event.repository.name, github.event.number) }}
      vault_addr: ${{ vars.vault_addr }}
      vault_k8s_role_path: ${{ vars.vault_k8s_staging_role_path }}
    secrets:
      OPENVPN_CONFIG: ${{ secrets.OPENVPN_CONFIG }}
  
  approve_candidate:
    uses: ptonini/gha-workflows/.github/workflows/retag-docker-image.yaml@main
    if: github.event.pull_request.merged
    needs:
      - start
    with:
      repository: ${{ format('{0}/{1}', vars.container_registry, github.event.repository.name ) }}
      source_tag: ${{ format('pr{0}', github.event.pull_request.number) }}
      tag: pr-approved
  
  promote_candidate:
    uses: ptonini/gha-workflows/.github/workflows/retag-docker-image.yaml@main
    if: github.event_name == 'push' && contains(github.event.commits.*.author.name, 'github-actions[bot]')
    needs:
      - start
    with:
      repository: ${{ format('{0}/{1}', vars.container_registry, github.event.repository.name ) }}
      source_tag: pr-approved
      tag: ${{ needs.start.outputs.release_version }}
  deploy_production:
    uses: ptonini/gha-workflows/.github/workflows/deploy-helm-releases.yaml@main
    needs:
      - promote_candidate
      - start
    with:
      vault_addr: ${{ vars.vault_addr }}
      vault_k8s_role_path: ${{ needs.start.outputs.vault_k8s_role_path }}
    secrets:
      OPENVPN_CONFIG: ${{ secrets.OPENVPN_CONFIG }}