name: publish

on:
  push:
    branches:
      - master
      - main
      - legacy/*
  pull_request:
    branches:
      - master
      - main
      - legacy/*

jobs:
  release_please:
    uses: ptonini/gha-workflows/.github/workflows/release-please.yaml@main
    if: github.event_name == 'push'
  
  startup:
    uses: ptonini/gha-workflows/.github/workflows/startup.yaml@main
    secrets:
      ORG_CONFIG: ${{ secrets.ORG_CONFIG }}
  
  unit_tests:
    uses: ptonini/gha-workflows/.github/workflows/unit-tests.yaml@main
    if: needs.startup.outputs.skip_tests == 'false'
    needs:
      - startup
  quality_scan:
    uses: ptonini/gha-workflows/.github/workflows/sonarcloud.yaml@main
    needs:
      - unit_tests
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  
  publish_artifact:
    uses: ptonini/gha-workflows/.github/workflows/publish-lua-rock.yaml@main
    needs:
      - startup
      - release_please
    with:
      release_created: ${{ needs.release_please.outputs.release_created }}
      tag_name: ${{ needs.release_please.outputs.tag_name }}
  
  code_linting:
    uses: ptonini/gha-workflows/.github/workflows/code-linting.yaml@main
    if: needs.startup.outputs.housekeeping == 'true'
    needs:
      - startup
  security_leaks_scan:
    uses: ptonini/gha-workflows/.github/workflows/trufflehog.yaml@main
    if: needs.startup.outputs.housekeeping == 'true'
    needs:
      - startup