name: publish

on:
  push:
    branches:
      - main
    paths:
      - charts/**

jobs:
  release_please:
    uses: ptonini/gha-workflows/.github/workflows/release-please.yaml@main
    if: github.event_name == 'push'
  
  publish:
    runs-on: ubuntu-latest
    if: needs.release_please.outputs.paths_released != '[]'
    needs:
      - release_please
    strategy:
      matrix:
        path: ${{ fromJSON(needs.release_please.outputs.paths_released) }}
    steps:
      - uses: actions/checkout@main
      - uses: actions/download-artifact@v2
      - run: echo "TAG_NAME=$(jq -r --arg A "${{ matrix.path }}--tag_name" '.[$A]' outputs)" >> $GITHUB_ENV
      - run: helm package --dependency-update ${{ matrix.path }}
      - uses: actions/upload-artifact@v3
        with:
          name: builds
          path: '*.tgz'
      - uses: svenstaro/upload-release-action@v2
        with:
          file: '*.tgz'
          file_glob: true
          tag: ${{ env.TAG_NAME }}
  update_repository:
    runs-on: ubuntu-latest
    needs:
      - publish
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v3
        with:
          name: builds
          path: ${{ github.workspace}}/builds
      - uses: dawidd6/action-git-user-config@v1
      - uses: helm/chart-releaser-action@v1.4.1
        with:
          install_only: true
      - run: cr index -p builds -i index.yaml --push
        env:
          CR_TOKEN: ${{ github.token}}
          CR_OWNER: ${{ github.event.repository.owner.name }}
          CR_GIT_REPO: ${{ github.event.repository.name }}
          CR_RELEASE_NAME_TEMPLATE: "{{ .Name }}-v{{ .Version }}"