name: publish

on:
  push:
    branches:
      - main
      - master
    paths:
      - rocks/**

jobs:
  release_please:
    uses: ptonini/gha-workflows/.github/workflows/release-please.yaml@main
    if: github.event_name == 'push'

  detect_changes:
    uses: ptonini/gha-workflows/.github/workflows/paths-filter.yaml@main

  publish_rocks:
    if: github.event_name == 'push' && contains(github.event.commits.*.author.name, 'github-actions[bot]') && needs.detect_changes.outputs.changes != '[]'
    needs:
      - detect_changes
    strategy:
      matrix:
        path: ${{ fromJSON(needs.detect_changes.outputs.changes) }}
    with:
      path: ${{ matrix.path }}
  update_repository:
    uses: ptonini/gha-workflows/.github/workflows/update-rocks-repository.yaml@main
    needs:
      - publish_rocks