name: publish

on:
  push:
    branches:
      - main
    paths:
      - charts/**

jobs:
  release_please:
    uses: ptonini/gha-workflows/.github/workflows/release-please.yaml@main
    if: github.event_name == 'push'
  publish_charts:
    runs-on: ubuntu-latest
    if: needs.release_please.outputs.paths_released != '[]'
    needs:
      - release_please
    strategy:
      matrix:
        path: ${{ fromJSON(needs.release_please.outputs.paths_released) }}
    steps:
      - uses: actions/checkout@main
      - uses: actions/download-artifact@v3
        with:
          name: release-please-outputs
      - run: echo "TAG_NAME=$(jq -r --arg A "${{ matrix.path }}--tag_name" '.[$A]' outputs)" >> $GITHUB_ENV
      - run: helm package --dependency-update ${{ matrix.path }}
      - uses: actions/upload-artifact@v3
        with:
          name: builds
          path: '*.tgz'
      - uses: svenstaro/upload-release-action@v2
        with:
          file: '*.tgz'
          file_glob: true
          tag: ${{ env.TAG_NAME }}
  update_repository:
    runs-on: ubuntu-latest
    needs:
      - publish_charts
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v3
        with:
          name: builds
          path: ${{ github.workspace}}/builds
      - uses: ptonini/gha-config-git-user@main
      - uses: helm/chart-releaser-action@v1.4.1
        with:
          install_only: true
      - run: cr index -p builds -i index.yaml -o ${{ github.event.repository.owner.name }} -t ${{ github.token}} -r ${{ github.event.repository.name }} --push --release-name-template "{{ .Name }}-v{{ .Version }}"