name: publish

on:
  push:
    branches:
      - master
      - main
      - legacy/*
  pull_request:
    branches:
      - master
      - main
      - legacy/*

jobs:
  
  code_testing:
    uses: ptonini/gha-workflows/.github/workflows/code-testing.yaml@main
    if: github.event.action != 'closed' && github.event.head_commit.author.name != 'github-actions[bot]' && !contains(github.event.repository.topics, 'skip-testing')
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  code_linting:
    uses: ptonini/gha-workflows/.github/workflows/code-linting.yaml@main
    if: github.event_name == 'pull_request' && contains('opened synchronize', github.event.action) && !contains(github.event.repository.topics, 'skip-linting')
  security_scan:
    uses: ptonini/gha-workflows/.github/workflows/trufflehog.yaml@main
    if: github.event_name == 'pull_request' && contains('opened synchronize', github.event.action)
  release_please:
    uses: ptonini/gha-workflows/.github/workflows/release-please.yaml@main
    if: github.event_name == 'push'
  
  start:
    uses: ptonini/gha-workflows/.github/workflows/start.yaml@main
  
  publish_artifact:
    uses: ptonini/gha-workflows/.github/workflows/publish-lua-rock.yaml@main
    needs:
      - start
      - release_please
    with:
      release_created: ${{ needs.release_please.outputs.release_created }}
      release_version: ${{ needs.start.outputs.release_version }}
      tag_name: ${{ needs.release_please.outputs.tag_name }}
