name: publish

on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - '.github/**'
      - '*'

jobs:
  release_please:
    uses: ptonini/gha-workflows/.github/workflows/release-please.yaml@main
    if: github.event_name == 'push'
  
  apply_releases:
    uses: ptonini/gha-workflows/.github/workflows/publish-docker-image.yaml@main
    if: needs.release_please.outputs.paths_released != '[]'
    needs:
      - release_please
    strategy:
      matrix:
        path: ${{ fromJSON(needs.release_please.outputs.paths_released) }}
    with:
      path: ${{ format('{1}/{2}', github.workspace, matrix.path }}
    secrets:
      ORG_CONFIG: ${{ secrets.ORG_CONFIG }}
      OPENVPN_CONFIG: ${{ secrets.OPENVPN_CONFIG }}
      VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
      VAULT_APPROLE_ROLE_ID: ${{ secrets.VAULT_APPROLE_ROLE_ID }}
      VAULT_APPROLE_SECRET_ID: ${{ secrets.VAULT_APPROLE_SECRET_ID }}