name: publish_terraform_module

concurrency:  ci-${{ github.ref }}

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  publish:
    uses: ptonini/gha-workflows/.github/workflows/publish-terraform-module.yaml@main
    secrets:
      TERRAFORM_CLOUD_TOKEN: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}