name: publish

on:
  push:
    branches:
      - main
    paths:
      - '*/*'

jobs:
  release_please:
    uses: ptonini/gha-workflows/.github/workflows/release-please.yaml@main
    if: github.event_name == 'push'
  
  publish:
    runs-on: ubuntu-latest
    if: needs.release_please.outputs.paths_released != '[]'
    needs:
      - release_please
    strategy:
      matrix:
        path: ${{ fromJSON(needs.release_please.outputs.paths_released) }}
    steps:
      - run: env | sort
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: release-please-outputs
      - run: echo "VERSION=$(jq -r --arg A "${{ matrix.path }}--version" '.[$A]' outputs)" | tee -a $GITHUB_ENV
      - uses: ptonini/gha-publish-docker-image@main
        with:
          repository: ${{ secrets.REPOSITORY_PREFIX }}/${{ matrix.path }}
          tags: latest ${{ env.VERSION }}
          path: ${{ github.workspace }}/${{ matrix.path }}