name: sync-repositories

on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/workflows/_*

jobs:
  detect_changes:
    uses: ptonini/gha-workflows/.github/workflows/detect-changes.yaml@main
    with:
      filters: |
        workflows:
          - '.github/workflows/*'
        src:
          - 'src/*'
        modules:
          - 'modules/**'
  sync_folders:
    runs-on: ubuntu-latest
    if: needs.detect_changes.outputs.changes != '[]'
    needs:
      - detect_changes
    strategy:
      matrix:
        repository: ${{ fromJson(vars.child_repositories) }}
    steps:
      - run: env | sort
      - uses: ptonini/gha-config-git-user@main
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: ${{ matrix.repository }}
          ssh-key: ${{ secrets.CHILD_REPOSITORY_DEPLOY_KEY_0 }}
          path: child_repository
      - run: sudo apt-get install -y rpl && rpl "${{ github.repository }}" "${{ matrix.repository }}" src/*
        if: contains(fromJson(needs.detect_changes.outputs.changes), 'src')
      - run: rsync -vr --exclude '.github/workflows/_*' --exclude 'child_repository' . child_repository
      - uses: EndBug/add-and-commit@v9
        with:
          cwd: ./child_repository
          message: "chore: synchronized from ${{ github.repository }}"