name: sync-repositories

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/*
      - '!.github/workflows/_*'
      - src/*
      - modules/**

jobs:
  detect_changes:
    uses: ptonini/gha-workflows/.github/workflows/detect-changes.yaml@main
    with:
      filters: |
        workflows:
          - '.github/workflows/*'
        src:
          - 'src/*'
        modules:
          - 'modules/**'
  sync_repositories:
    runs-on: ubuntu-latest
    if: needs.detect_changes.outputs.changes != '[]'
    needs:
      - detect_changes
    strategy:
      matrix:
        repository: ${{ fromJson(vars.child_repositories) }}
    steps:
      - run: env | sort
      - uses: ptonini/gha-config-git-user@main
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: ${{ matrix.repository }}
          ssh-key: ${{ secrets.SSH_KEY }}
          path: child_repository
      - run: | 
          sudo apt-get install -y rpl
          rpl "${{ github.repository }}" "${{ matrix.repository }}" src/*
          rsync -vr src child_repository
        if: contains(fromJson(needs.detect_changes.outputs.changes), 'src')
      - run: rsync -vr modules child_repository
        if: contains(fromJson(needs.detect_changes.outputs.changes), 'modules')
      - run: rsync -vr --exclude '_*' .github/workflows child_repository/.github
        if: contains(fromJson(needs.detect_changes.outputs.changes), 'workflows')
      - uses: EndBug/add-and-commit@v9
        with:
          cwd: ./child_repository
          message: "chore: synchronized from ${{ github.repository }} [skip ci]"