name: approve-image

on:
  workflow_call:
    inputs:
      repository:
        description: ''
        required: false
        default: ${{ format('{0}/{1}', vars.container_registry, github.event.repository.name ) }}
        type: string

jobs:
  approve_image:
    runs-on: ubuntu-latest
    steps:
      - run: env | sort
      - run: cat ${GITHUB_EVENT_PATH}
      - uses: ptonini/gha-retag-docker-image@main
        with:
          registry: ${{ vars.container_registry }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
          repository: ${{ inputs.repository }}
          source_tag: ${{ format('pr{ 0 }', github.event.number) }}
          tags: latest ${{ vars.pr_approved_tag }} ${{ format('pr{0}', github.event.number) }}