name: deploy-helm-releases

on:
  workflow_call:
    inputs:
      checksum:
        description: ''
        default: ''
        type: string
    secrets:
      OPENVPN_CONFIG:
        description: ''
        required: true
      VAULT_ADDR:
        description: ''
        required: true
      VAULT_APPROLE_ROLE_ID:
        description: ''
        required: true
      VAULT_APPROLE_SECRET_ID:
        description: ''
        required: true

jobs:
  deploy_helm_releases:
    runs-on: ubuntu-latest
    steps:
      - run: env | sort
      - uses: ptonini/gha-load-metadata@main
      - uses: ptonini/gha-openvpn@main
        with:
          openvpn_config: ${{ secrets.OPENVPN_CONFIG }}
          validation_addr: ${{ secrets.VAULT_ADDR }}
      - uses: hashicorp/vault-action@v2.3.0
        with:
          method: approle
          url: ${{ secrets.VAULT_ADDR }}
          roleId: ${{ secrets.VAULT_APPROLE_ROLE_ID }}
          secretId: ${{ secrets.VAULT_APPROLE_SECRET_ID }}
          secrets: |
            ${{ env.VAULT_GITHUB_TOKEN_PATH }} token | GH_TOKEN;
            ${{ env.VAULT_REGISTRY_CREDENTIALS_PATH }} dockerconfigjson | REGISTRY_CREDENTIALS;
            ${{ env.VAULT_K8S_ROLE_PATH }} kube_config | KUBECONFIG_CONTENT;
      - uses: ptonini/gha-prepare-helm-releases@main
        id: releases
        with:
          github_token: ${{ env.GH_TOKEN }}
          checksum: ${{ inputs.checksum }}
      - uses: actions/upload-artifact@v3
        with:
          name: releases
          path: ${{ github.workspace }}/**
      - uses: ptonini/gha-deploy-helm-releases@main
        with:
          kubeconfig_content: ${{ env.KUBECONFIG_CONTENT }}
          releases: ${{ steps.releases.outputs.releases }}
