name: deploy-helm-releases

on:
  workflow_call:
    inputs:
      environment:
        description: ''
        required: false
        type: string
      namespace:
        description: ''
        required: false
        type: string
      digest:
        description: ''
        required: false
        type: string
      vault_k8s_role_path:
        description: ''
        required: true
        type: string
      vault_github_token_path:
        description: ''
        required: false
        type: string
    secrets:
      OPENVPN_CONFIG:
        description: ''
        required: true
    outputs:
      hostnames:
        description: ''
        value: ${{ jobs.deploy_helm_releases.outputs.hostnames }}

jobs:
  deploy_helm_releases:
    runs-on: ubuntu-latest
    outputs:
      hostnames: ${{ steps.releases.outputs.hostnames }}
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - run: env | sort
      - uses: ptonini/gha-openvpn@main
        with:
          openvpn_config: ${{ secrets.OPENVPN_CONFIG }}
          validation_addr: ${{ vars.vault_addr }}
      - uses: hashicorp/vault-action@v2.4.3
        with:
          url: ${{ vars.vault_addr }}
          method: ${{ vars.vault_method }}
          path: ${{ vars.vault_path }}
          role: ${{ vars.vault_role }}
          exportToken: true
          secrets: ${{ inputs.vault_k8s_role_path }} kube_config | KUBECONFIG_CONTENT;
      - uses: hashicorp/vault-action@v2.4.3
        if: inputs.vault_github_token_path
        with:
          url: ${{ vars.vault_addr }}
          token: ${{ env.VAULT_TOKEN }}
          secrets: ${{ inputs.vault_github_token_path }} token | GH_TOKEN;
      - uses: ptonini/gha-prepare-helm-releases@main
        id: releases
        with:
          digest: ${{ inputs.digest }}
          namespace: ${{ inputs.namespace }}
          environment: ${{ inputs.environment }}
          github_token: ${{ env.GH_TOKEN }}
          manifest_file: ${{ vars.manifest_file }}
          rp_manifest_file: ${{ vars.rp_manifest_file }}
          ingress_configs_repository: ${{ vars.ingress_configs_repository }}
          org_domain: ${{ vars.org_domain }}
          app_groups: ${{ vars.app_groups }}
      - uses: actions/upload-artifact@v3
        with:
          name: releases
          path: ${{ github.workspace }}/**
      - uses: ptonini/gha-deploy-helm-releases@main
        with:
          kubeconfig_content: ${{ env.KUBECONFIG_CONTENT }}
          releases: ${{ steps.releases.outputs.releases }}
      - uses: thollander/actions-comment-pull-request@v1
        if: steps.releases.outputs.message
        with:
          message: ${{ steps.releases.outputs.message }}
          comment_includes: ${{ steps.releases.outputs.message }}
