name: destroy-staging

on:
  workflow_call:
    inputs:
      vault_k8s_role_path:
        description: ''
        required: true
        type: string
    secrets:
      OPENVPN_CONFIG:
        description: ''
        required: true

env:
  AWS_REGION: us-east-1

jobs:
  destroy_staging:
    runs-on: ubuntu-latest
    steps:
      - run: env | sort
      - uses: ptonini/gha-openvpn@main
        with:
          openvpn_config: ${{ secrets.OPENVPN_CONFIG }}
          validation_addr: ${{ vars.vault_addr }}
      - uses: hashicorp/vault-action@v2.4.3
        with:
          method: ${{ vars.vault_method }}
          path: ${{ vars.vault_path }}
          role: ${{ vars.vault_role }}
          url: ${{ vars.vault_addr }}
          secrets: ${{ inputs.vault_k8s_role_path }} kube_config | KUBECONFIG_CONTENT;
      - run: echo "${KUBECONFIG_CONTENT}" > kubeconfig && chmod 0600 kubeconfig && echo "KUBECONFIG=kubeconfig" | tee -a ${GITHUB_ENV}
      - run: echo "STAGING_NAMESPACE=$(tr _ - <<< ${{ github.event.repository.name }})-${{ github.event.number }}" | tee -a ${GITHUB_ENV}
      - run: helm --namespace ${STAGING_NAMESPACE} list --short | xargs -r helm uninstall --namespace ${STAGING_NAMESPACE}
      - run: kubectl delete all --all --namespace ${STAGING_NAMESPACE}
      - run: kubectl get namespace ${STAGING_NAMESPACE} && kubectl delete namespace ${STAGING_NAMESPACE}