name: destroy-staging

on:
  workflow_call:
    inputs:
      namespace:
        description: ''
        required: true
        type: string
      vault_method:
        description: ''
        default: jwt
        required: false
        type: string
      vault_path:
        description: ''
        default: oidc/github
        required: false
        type: string
      vault_role:
        description: ''
        default: workflow
        required: false
        type: string
    secrets:
      OPENVPN_CONFIG:
        description: ''
        required: true
      VAULT_ADDR:
        description: ''
        required: true
      VAULT_K8S_ROLE_PATH:
        description: ''
        required: true

env:
  AWS_REGION: us-east-1

jobs:
  destroy_staging:
    runs-on: ubuntu-latest
    steps:
      - run: env | sort
      - uses: ptonini/gha-load-metadata@main
      - uses: ptonini/gha-openvpn@main
        with:
          openvpn_config: ${{ secrets.OPENVPN_CONFIG }}
          validation_addr: ${{ secrets.VAULT_ADDR }}
      - uses: hashicorp/vault-action@v2.4.2
        with:
          method: ${{ inputs.vault_method }}
          path: ${{ inputs.vault_path }}
          role: ${{ inputs.vault_role }}
          url: ${{ secrets.VAULT_ADDR }}
          secrets: ${{ secrets.VAULT_K8S_ROLE_PATH }} kube_config | KUBECONFIG_CONTENT;
      - run: echo "${KUBECONFIG_CONTENT}" > kubeconfig && chmod 0600 kubeconfig && echo "KUBECONFIG=kubeconfig" >> ${GITHUB_ENV}
      - run: helm --namespace ${{ inputs.namespace }} list --short | xargs -r helm uninstall --namespace ${{ inputs.namespace }}
      - run: kubectl delete all --all --namespace ${{ inputs.namespace }}
      - run: kubectl get namespace ${{ inputs.namespace }} && kubectl delete namespace ${{ inputs.namespace }} || true