name: destroy-staging

on:
  workflow_call:
    inputs:
      vault_k8s_role_path:
        description: ''
        required: true
        type: string
    secrets:
      OPENVPN_CONFIG:
        description: ''
        required: true

env:
  AWS_REGION: us-east-1

jobs:
  destroy_staging:
    runs-on: ubuntu-latest
    steps:
      - run: env | sort
      - run: cat ${GITHUB_EVENT_PATH}
      - uses: ptonini/gha-openvpn@main
        with:
          openvpn_config: ${{ secrets.OPENVPN_CONFIG }}
          validation_addr: ${{ vars.vault_addr }}
      - uses: hashicorp/vault-action@v2
        with:
          method: ${{ vars.vault_method }}
          path: ${{ vars.vault_path }}
          role: ${{ vars.vault_role }}
          url: ${{ vars.vault_addr }}
          secrets: ${{ inputs.vault_k8s_role_path }} kube_config | KUBECONFIG_MANIFEST;
      - uses: ptonini/gha-get-labels@main
        with:
          labels: namespace
      - run: echo "${KUBECONFIG_MANIFEST}" > kubeconfig && chmod 0600 kubeconfig && echo "KUBECONFIG=kubeconfig" | tee -a ${GITHUB_ENV}
      - run: helm list --short --namespace ${NAMESPACE} | xargs -r helm uninstall --namespace ${NAMESPACE}
      - run: kubectl delete all --all --namespace ${NAMESPACE}
      - run: kubectl delete namespace ${NAMESPACE}