name: destroy-namespace

on:
  workflow_call:
    secrets:
      OPENVPN_CONFIG:
        description: ''
        required: true

jobs:
  destroy_namespace:
    runs-on: ubuntu-latest
    env:
      KUBECONFIG: ${{ github.workspace }}/.kube/config
    steps:
      - run: env | sort
      - run: cat ${GITHUB_EVENT_PATH}
      - uses: ptonini/gha-openvpn@main
        with:
          openvpn_config: ${{ secrets.OPENVPN_CONFIG }}
          validation_addr: ${{ vars.ovpn_validation_addr }}
      - uses: ptonini/gha-cloud-login@main
        with:
          vault_addr: ${{ vars.vault_addr }}
          vault_method: ${{ vars.vault_method }}
          vault_path: ${{ vars.vault_path }}
          vault_role: ${{ vars.vault_role }}
          aws_region: ${{ vars.aws_region }}
          aws_role: ${{ vars.aws_role }}
          azure_tenant_id: ${{ vars.azure_tenant_id }}
          azure_subscription_id: ${{ vars.azure_subscription_id }}
          azure_client_id: ${{ vars.azure_client_id }}
          openstack_config: ${{ secrets.OPENSTACK_CONFIG }}
      - uses: ptonini/gha-get-kubeconfig@main
        with:
          cluster_name: ${{ vars.kubernetes_cluster_name }}
          kubeconfig_source: ${{ vars.kubeconfig_source }}
          vault_addr: ${{ vars.vault_addr }}
          aws_region: ${{ vars.aws_region }}
          azure_resource_group: ${{ vars.azure_resource_group }}
      - uses: ptonini/gha-get-labels@main
        with:
          labels: namespace
      - run: helm list --short --namespace ${NAMESPACE} | xargs -r helm uninstall --namespace ${NAMESPACE}
      - run: kubectl delete all --all --namespace ${NAMESPACE}
      - run: kubectl delete namespace ${NAMESPACE}