name: detect-changes

on:
  workflow_call:
    outputs:
      changes:
        description: ''
        value: ${{ jobs.detect_changes.outputs.changes }}

jobs:
  detect_changes:
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.filter.outputs.changes }}
    steps:
      - run: env | sort
      - run: jq . ${{ github.event_path }}
      - uses: actions/checkout@main
      - run: '[[ -e ./filters.yaml ]] || bash build_filters > filters.yaml'
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: filters.yaml