name: detect-changes

on:
  workflow_call:
    inputs:
      filters:
        description: ''
        default: filters.yaml
        required: false
        type: string
      filters_cmd:
        description: ''
        required: false
        type: string
    outputs:
      changes:
        description: ''
        value: ${{ jobs.detect_changes.outputs.changes }}

jobs:
  detect_changes:
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.filter.outputs.changes }}
    steps:
      - run: env | sort
      - uses: actions/checkout@v3
      - run: jq -r '.packages | keys | reduce .[] as $i ({}; .[$i] = $i+"/*")' release-please-config.json > ${{ inputs.filters }}
        if: hashFiles('release-please-config.json')
      - run: ${{ inputs.filters_cmd }} > ${{ inputs.filters }}
        if: inputs.filters_cmd
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: ${{ inputs.filters }}