name: performance-testing

on:
  workflow_call:
    inputs:
      filename:
        description: ''
        required: false
        type: string
      hostnames:
        description: ''
        required: true
        type: string

jobs:
  performance_testing:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - run: env | sort
      - uses: actions/checkout@v3
      - run: until nslookup ${{ inputs.hostname }}; do sleep 10; done
      - uses: grafana/k6-action@v0.2.0
        if: hashFiles('k6-tests.js')
        with:
          filename: ${{ inputs.filename }}
          flags: --env HOSTNAMES=${{ inputs.hostnames }}