name: performance-testing

on:
  workflow_call:
    inputs:
      host:
        description: ''
        required: true
        type: string

jobs:
  performance_testing:
    timeout-minutes: ${{ vars.performance_test_timeout }}
    runs-on: ubuntu-latest
    steps:
      - run: env | sort
      - run: cat ${GITHUB_EVENT_PATH}
      - uses: actions/checkout@v3
      - uses: grafana/k6-action@v0.2.0
        if: hashFiles(vars.k6_test_file)
        with:
          filename: ${{ vars.k6_test_file }}
        env:
          HOST: ${{ inputs.host }}
          SCHEMA: https