name: performance-testing

on:
  workflow_call:
    inputs:
      hosts:
        description: ''
        required: true
        type: string

jobs:
  performance_testing:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - run: env | sort
      - uses: actions/checkout@v3
      - uses: grafana/k6-action@v0.2.0
        if: hashFiles(vars.k6_test_file)
        with:
          filename: ${{ vars.k6_test_file }}
          flags: --env HOSTS=${{ inputs.hosts }}