name: publish-monorepo-luarock

on:
  workflow_call:
    inputs:
      path:
        description: ''
        required: true
        type: string

jobs:
  publish_monorepo_luarock:
    runs-on: ubuntu-latest
    steps:
      - run: env | sort
      - run: cat ${GITHUB_EVENT_PATH}
      - uses: actions/checkout@v3
      - uses: leafo/gh-actions-lua@10
        with:
          luaVersion: ${{ vars.lua_version }}
      - uses: leafo/gh-actions-luarocks@v4
      - run: echo "ROCK=$(basename ${{ inputs.path }})" | tee -a $GITHUB_ENV
      - run: echo "VERSION=$(jq -r '."${{ inputs.path }}"' ${{ vars.rp_manifest_file }})" | tee -a $GITHUB_ENV
      - run: tar -czvC rocks -f ${{ inputs.path }}.tar.gz ${ROCK}
      - run: envsubst < ${{ inputs.path }}/rockspec > ${ROCK}-${VERSION}-1.rockspec
      - run: luarocks pack ${ROCK}-${VERSION}-1.rockspec
      - uses: ptonini/gha-upload-release@main
        with:
          file: ${{ env.ROCK }}-${{ env.VERSION }}-*
          file_glob: true
          tag: ${{ env.ROCK }}-v${{ env.VERSION }}
          overwrite: true
      - uses: actions/upload-artifact@v3
        with:
          name: rocks
          path: ${{ env.PACKAGE }}-${{ env.VERSION }}-*