name: publish-docker-collection

on:
  workflow_call:
    inputs:
      image:
        description: ''
        required: true
        type: string
    secrets:
      REPOSITORY_PREFIX:
        description: ''
        required: true
    outputs:
      checksum:
        description: ''
        value: ${{ jobs.publish_docker_image.outputs.checksum }}
    
jobs:
  publish_docker_image:
    runs-on: ubuntu-latest
    outputs:
      checksum: ${{ steps.publish_image.outputs.checksum }}
    steps:
      - run: env | sort
      - uses: actions/checkout@main
      - uses: actions/download-artifact@v2
        with:
          name: release-please-outputs
      - run: echo "VERSION=$(jq -r --arg A "${{ inputs.image }}--version" '.[$A]' outputs)" >> $GITHUB_ENV
      - uses: ptonini/gha-publish-docker-image@main
        id: publish_image
        with:
          repository: ${{ secrets.REPOSITORY_PREFIX }}/${{ inputs.image }}
          tags: latest ${{ env.VERSION }}
          path: ${{ github.workspace }}/${{ inputs.image }}