name: publish-lua-rock

on:
  workflow_call:
    inputs:
      tag_name:
        description: ''
        required: true
        type: string
      release_created:
        description: ''
        required: true
        type: string
        
jobs:
  publish_lua_rock:
    runs-on: ubuntu-latest
    steps:
      - run: env | sort
      - uses: actions/checkout@main
      - uses: ptonini/gha-load-metadata@main
      - uses: leafo/gh-actions-lua@v9
      - uses: leafo/gh-actions-luarocks@v4
      - run: cat template.rockspec | envsubst > ${ROCK_FILE}
      - run: luarocks pack ${ROCK_FILE}
      - uses: actions/upload-artifact@v3
        with:
          name: luarock
          path: ${{ env.ROCK_PREFIX }}-0.*
      - uses: svenstaro/upload-release-action@v2
        if: inputs.release_created == 'true'
        with:
          file: ${{ env.ROCK_PREFIX }}-0.*
          file_glob: true
          repo_token: ${{ github.token }}
          tag: ${{ inputs.tag_name }}
