name: publish-helm-charts

on:
  workflow_call:
    inputs:
      path:
        description: ''
        required: true
        type: string
      packages:
        description: ''
        required: true
        type: string

jobs:
  publish_charts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "PACKAGE=$(jq -r '."${{ inputs.path }}".package_name' <<< '${{ inputs.packages }}')" | tee -a $GITHUB_ENV
      - run: echo "TAG_NAME=$(jq -r  '."${{ inputs.path }}".tag_name' <<< '${{ inputs.packages }}')" | tee -a $GITHUB_ENV
      - run: echo "VERSION=$(jq -r  '."${{ inputs.path }}".version' <<< '${{ inputs.packages }}')" | tee -a $GITHUB_ENV
      - run: helm package --dependency-update ${{ matrix.path }}
      - uses: ptonini/gha-upload-release@main
        with:
          file: ${{ env.PACKAGE }}-${{ env.VERSION }}.tgz
          tag: ${{ env.TAG_NAME }}