name: publish-go-application

on:
  workflow_call:
    inputs:
      tag_name:
        description: ''
        required: true
        type: string
      release_created:
        description: ''
        required: true
        type: string
  
jobs:
  publish_go_application:
    runs-on: ubuntu-latest
    steps:
      - run: env | sort
      - uses: actions/checkout@main
      - uses: ptonini/gha-load-metadata@main
      - run: mkdir dist
      - run: docker run -v $(pwd):$(pwd) -w $(pwd) ${GO_BUILDER_IMAGE} go build -o dist/${GO_APP_NAME} ${GO_MAIN_FILE}
      - run: sha256sum dist/${GO_APP_NAME} > dist/SHA256SUMS
      - uses: actions/upload-artifact@v3
        with:
          name: application
          path: dist/**
      - uses: svenstaro/upload-release-action@v2
        if: inputs.release_created == 'true'
        with:
          file: dist/**
          file_blob: true
          repo_token: ${{ github.token }}
          tag: ${{ inputs.tag_name }}