name: publish-go-application

on:
  workflow_call:
    inputs:
      app_name:
        description: ''
        default: ${{ github.event.repository.name }}
        required: false
        type: string

jobs:
  publish_go_application:
    runs-on: ubuntu-latest
    steps:
      - run: env | sort
      - run: cat ${GITHUB_EVENT_PATH}
      - uses: actions/checkout@v3
      - run: echo "VERSION=$(jq -r '."."' < ${{ vars.rp_manifest_file }})" | tee -a $GITHUB_ENV
      - run: mkdir dist
      - run: docker run -v $(pwd):$(pwd) -w $(pwd) ${{ vars.go_builder_image }} go build -o dist/${{ inputs.app_name }} ${{ vars.go_main_file }}
      - run: sha256sum dist/${{ inputs.app_name }} > dist/SHA256SUMS
      - uses: ptonini/gha-upload-release@main
        with:
          file: dist/${{ inputs.app_name }}
          tag: v${{ env.VERSION }}