name: publish-frontend

on:
  workflow_call:
    inputs:
      tag_name:
        description: ''
        required: true
        type: string
    secrets:
      NPM_TOKEN:
        description: ''
        required: false

jobs:
  publish_frontend:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ github.token }}
    steps:
      - run: env | sort
      - uses: actions/checkout@v3
      - uses: ptonini/gha-load-metadata@main
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ vars.nodejs_version }}
      - run: yarn install --prod && yarn build
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: tar czvf ${ARTIFACT_FILENAME} build
      - uses: ptonini/gha-upload-release@main
        with:
          file: ${{ env.ARTIFACT_FILENAME }}
          repo_token: ${{ github.token }}
          tag: ${{ inputs.tag_name }}
