name: publish-lua-rock

on:
  workflow_call:
    inputs:
      path:
        description: ''
        required: true
        type: string
      packages:
        description: ''
        required: true
        type: string

jobs:
  publish_lua_rocks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: leafo/gh-actions-lua@v9
      - uses: leafo/gh-actions-luarocks@v4
      - run: echo "PACKAGE=$(jq -r '."${{ inputs.path }}".package_name' <<< '${{ inputs.packages }}')" | tee -a $GITHUB_ENV
      - run: echo "TAG_NAME=$(jq -r  '."${{ inputs.path }}".tag_name' <<< '${{ inputs.packages }}')" | tee -a $GITHUB_ENV
      - run: echo "VERSION=$(jq -r  '."${{ inputs.path }}".version' <<< '${{ inputs.packages }}')" | tee -a $GITHUB_ENV
      - run: tar -czvC rocks -f ${{ inputs.path }}.tar.gz ${PACKAGE}
      - run: envsubst < ${{ inputs.path }}/rockspec > ${PACKAGE}-${VERSION}-1.rockspec
      - run: luarocks pack ${PACKAGE}-${VERSION}-1.rockspec
      - uses: actions/upload-artifact@v3
        with:
          name: rocks
          path: ${{ env.PACKAGE }}-${{ env.VERSION }}-*
      - uses: ptonini/gha-upload-release@main
        with:
          file: ${{ env.PACKAGE }}-${{ env.VERSION }}-*
          file_glob: true
          repo_token: ${{ github.token }}
          tag: ${{ env.TAG_NAME }}