name: publish-helm-chart

on:
  workflow_call:
    inputs:
      chart:
        description: ''
        required: true
        type: string

        
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - run: echo CHART_VERSION=$(helm show chart charts/${{ inputs.chart }} | grep -e '^version' | awk '{print $2}') >> $GITHUB_ENV
      - run: helm dependency build charts/${{ inputs.chart }}
      - run: helm package charts/${{ inputs.chart }}
      - uses: actions/upload-artifact@v3
        with:
          name: builds
          path: ${{ inputs.chart }}-${{ env.CHART_VERSION }}.tgz
      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ github.token }}
          file: ${{ inputs.chart }}-${{ env.CHART_VERSION }}.tgz
          tag: ${{ inputs.chart }}-v${{ env.CHART_VERSION }}