name: publish-docker-image

on:
  workflow_call:
    inputs:
      repository:
        description: ''
        required: true
        type: string
      tags:
        description: ''
        required: true
        type: string
    secrets:
      BUILD_ARGUMENTS:
        description: ''
        required: false
    outputs:
      digest:
        description: ''
        value: ${{ jobs.publish_docker_image.outputs.digest }}

jobs:
  publish_docker_image:
    runs-on: ubuntu-latest
    outputs:
      digest: ${{ steps.publish_image.outputs.digest }}
    steps:
      - run: env | sort
      - uses: actions/checkout@v3
      - uses: ptonini/gha-publish-docker-image@main
        id: publish_image
        with:
          registry: ${{ vars.container_registry }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
          repository: ${{ inputs.repository }}
          tags: ${{ inputs.tags }}
          build_arguments: ${{ secrets.BUILD_ARGUMENTS }}