name: read-manifests

on:
  workflow_call:
    inputs:
      vault_k8s_role_paths:
        description: ''
        required: false
        type: string
    outputs:
      release_version:
        description: ''
        value: ${{ jobs.startup.outputs.release_version }}
      vault_k8s_role_path:
        description: ''
        value: ${{ jobs.startup.outputs.vault_k8s_role_path }}
      
jobs:
  read_manifests:
    runs-on: ubuntu-latest
    outputs:
      release_version: ${{ steps.get_metadata.outputs.release_version }}
      vault_k8s_role_path: ${{ steps.get_metadata.outputs.vault_k8s_role_path }}
    steps:
      - run: env | sort
      - run: cat $GITHUB_EVENT_PATH
      - uses: actions/checkout@v3
      - uses: ptonini/gha-get-metadata@main
        id: get_metadata
        with:
          vault_k8s_role_paths: ${{ inputs.vault_k8s_role_paths }}