name: release-please

on:
  workflow_call:
    outputs:
      release_created:
        description: ''
        value: ${{ jobs.release_please.outputs.release_created }}
      releases_created:
        description: ''
        value: ${{ jobs.release_please.outputs.releases_created }}
      tag_name:
        description: ''
        value: ${{ jobs.release_please.outputs.tag_name }}
      paths_released:
        description: ''
        value: ${{ jobs.release_please.outputs.paths_released }}
      full_output:
        description: ''
        value: ${{ jobs.release_please.outputs.full_output }}

jobs:
  release_please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      releases_created: ${{ steps.release.outputs.releases_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
      paths_released: ${{ steps.release.outputs.paths_released }}
      full_output: ${{ toJson(steps.release.outputs) }}
    steps:
      - run: env | sort
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          command: manifest
      - run: echo '${{ toJson(steps.release.outputs) }}' | tee outputs
      - uses: actions/upload-artifact@v3
        with:
          name: release-please-outputs
          path: outputs
