name: release-please

on:
  workflow_call:
    outputs:
      release_created:
        description: ''
        value: ${{ jobs.release_please.outputs.release_created }}
      releases_created:
        description: ''
        value: ${{ jobs.release_please.outputs.releases_created }}
      tag_name:
        description: ''
        value: ${{ jobs.release_please.outputs.tag_name }}
      full_output:
        description: ''
        value: ${{ jobs.release_please.outputs.full_output }}

jobs:
  release_please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      releases_created: ${{ steps.release.outputs.releases_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
      full_output: ${{ steps.full_output.outputs.full_output }}
    steps:
      - run: env | sort
      - uses: actions/checkout@main
        with:
          fetch-depth: 0
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          command: manifest
      - id: full_output  
        run: |
            content="${{ toJSON(steps.release.outputs) }}"
            # the following lines are only required for multi line json
            content="${content//'%'/'%25'}"
            content="${content//$'\n'/'%0A'}"
            content="${content//$'\r'/'%0D'}"
            # end of optional handling for multi line json
            echo "::set-output name=full_output::$content"
