name: retag-docker-image

on:
  workflow_call:
    inputs:
      registry:
        description: ''
        required: false
        default: ghcr.io
        type: string
      repository:
        description: ''
        required: true
        type: string
      source_tag:
        description: ''
        required: true
        type: string
      tag:
        description: ''
        required: true
        type: string
    secrets:
      USERNAME:
        description: ''
        required: false
      PASSWORD:
        description: ''
        required: false

jobs:
  retag_docker_image:
    runs-on: ubuntu-latest
    steps:
      - run: env | sort
      - run: echo "USERNAME=$([[ -n "${{ secrets.USERNAME }}" ]] && echo "${{ secrets.USERNAME }}" || echo "${{ github.actor }}" )" | tee -a $GITHUB_ENV
      - run: echo "PASSWORD=$([[ -n "${{ secrets.PASSWORD }}" ]] && echo "${{ secrets.PASSWORD }}" || echo "${{ secrets.GITHUB_TOKEN }}" )" | tee -a $GITHUB_ENV
      - uses: docker/login-action@v2
        with:
          registry: ${{ inputs.registry }}
          username: ${{ env.USERNAME }}
          password: ${{ env.PASSWORD }}
      - run: docker pull ${{ inputs.repository }}:${{ inputs.source_tag }}
      - run: docker tag ${{ inputs.repository }}:${{ inputs.source_tag }} ${{ inputs.repository }}:${{ inputs.tag }}
      - run: docker push ${{ inputs.repository }}:${{ inputs.tag }}

