name: retag-docker-image

on:
  workflow_call:
    inputs:
      source_tag:
        description: ''
        required: true
        type: string
      tag:
        description: ''
        required: true
        type: string
      registry:
        description: ''
        required: false
        default: ghcr.io
        type: string
    secrets:
      USERNAME:
        description: ''
        required: false
      PASSWORD:
        description: ''
        required: false

jobs:
  retag_docker_image:
    runs-on: ubuntu-latest
    steps:
      - run: env | sort
      - uses: ptonini/gha-load-metadata@main
      - run: echo "USERNAME=$([[ -n "${{ secrets.USERNAME }}" ]] && echo "${{ secrets.USERNAME }}" || echo "${{ github.actor }}" )" >> $GITHUB_ENV
      - run: echo "PASSWORD=$([[ -n "${{ secrets.PASSWORD }}" ]] && echo "${{ secrets.PASSWORD }}" || echo "${{ secrets.GITHUB_TOKEN }}" )" >> $GITHUB_ENV
      - uses: docker/login-action@v1
        with:
          registry: ${{ inputs.registry }}
          username: ${{ env.USERNAME }}
          password: ${{ env.PASSWORD }}
      - run: docker pull ${DOCKER_IMAGE_NAME}:${{ inputs.source_tag }}
      - run: docker tag ${DOCKER_IMAGE_NAME}:${{ inputs.source_tag }} ${DOCKER_IMAGE_NAME}:${{ inputs.tag }}
      - run: docker push ${DOCKER_IMAGE_NAME}:${{ inputs.tag }}

