name: startup

on:
  workflow_call:
    secrets:
      VAULT_K8S_ROLE_PATHS:
        description: ''
        required: false
    outputs:
      release_version:
        description: ''
        value: ${{ jobs.startup.outputs.release_version }}
      docker_repository:
        description: ''
        value: ${{ jobs.startup.outputs.docker_repository }}
      vault_k8s_role_path:
        description: ''
        value: ${{ jobs.startup.outputs.vault_k8s_role_path }}
      
jobs:
  startup:
    runs-on: ubuntu-latest
    outputs:
      release_version: ${{ steps.get_metadata.outputs.release_version }}
      docker_repository: ${{ steps.get_metadata.outputs.docker_repository }}
      vault_k8s_role_path: ${{ steps.get_metadata.outputs.vault_k8s_role_path }}
    steps:
      - run: env | sort
      - run: cat $GITHUB_EVENT_PATH
      - uses: actions/checkout@v3
      - uses: ptonini/gha-get-metadata@main
        id: get_metadata
        with:
          vault_k8s_role_paths: ${{ secrets.VAULT_K8S_ROLE_PATHS }}