name: trufflehog

on:
  workflow_call:
  
jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - run: env | sort
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: "[[ ! -e .trufflehog-ignore ]] || echo 'TRUFFLEHOG_EXTRA_ARGS=--exclude-paths=.trufflehog-ignore' >> $GITHUB_ENV"
      - run: "[[ -z ${RUNNER_DEBUG} ]] || 'TRUFFLEHOG_EXTRA_ARGS={{ env.TRUFFLEHOG_EXTRA_ARGS }} --debug' >> $GITHUB_ENV"
      - uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --max-depth=3 ${{ env.TRUFFLEHOG_EXTRA_ARGS }}