name: trufflehog

on:
  workflow_call:
  
jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - run: env | sort
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --max-depth=3