name: uninstall-helm-release

on:
  workflow_call:
    inputs:
      vault_k8s_role_path:
        description: ''
        required: true
        type: string
    secrets:
      OPENVPN_CONFIG:
        description: ''
        required: true

jobs:
  uninstall_helm_release:
    runs-on: ubuntu-latest
    steps:
      - run: env | sort
      - run: cat ${GITHUB_EVENT_PATH}
      - uses: ptonini/gha-openvpn@main
        with:
          openvpn_config: ${{ secrets.OPENVPN_CONFIG }}
          validation_addr: ${{ vars.vault_addr }}
      - uses: hashicorp/vault-action@v2
        with:
          url: ${{ vars.vault_addr }}
          method: ${{ vars.vault_method }}
          path: ${{ vars.vault_path }}
          role: ${{ vars.vault_role }}
          secrets: ${{ inputs.vault_k8s_role_path }} kube_config | KUBECONFIG;
      - uses: ptonini/gha-create-helm-release-files@main
        id: releases
        with:
          container_registry: ${{ vars.container_registry }}
          manifest_file: ${{ vars.manifest_file }}
          rp_manifest_file: ${{ vars.rp_manifest_file }}
          staging_domain: ${{ vars.staging_domain }}
      - uses: ptonini/gha-uninstall-helm-releases@main
        with:
          releases: ${{ steps.releases.outputs.releases }}
          kubeconfig: ${{ env.KUBECONFIG }}