name: unit-tests

on:
  workflow_call:

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - run: env | sort
      - uses: actions/checkout@main
      - uses: ptonini/gha-load-metadata@main
      - run: mkdir -p ${{ env.REPORTS_FOLDER }}
      - run: touch ${{ env.REPORTS_FOLDER }}/.placeholder
      - uses: ptonini/gha-go-tests@main
        if: github.event.repository.language == 'Go'
        with:
          reports_folder: ${{ env.REPORTS_FOLDER }}
          coverage_profile: ${{ env.GO_COVERAGE_PROFILE }}
          test_report: ${{ env.GO_TEST_REPORT }}
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ env.REPORTS_FOLDER }}
          path: ${{ env.REPORTS_FOLDER }}
