name: update-rocks-repository

on:
  workflow_call:

jobs:
  update_rocks_repository:
    runs-on: ubuntu-latest
    steps:
      - run: env | sort
      - run: cat ${GITHUB_EVENT_PATH}
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
      - uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: ${{ vars.lua_version }}
      - uses: leafo/gh-actions-luarocks@v4
      - uses: actions/download-artifact@v3
        with:
          name: rocks
      - run: luarocks-admin make-manifest --local-tree ${{ github.workspace }}
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .